### ISSUE TITLE
Validate API fails on kernel versions > 5.7 

### ISSUE THREAD

**Issue by the-rectifier** [vsamtuc/tinyos3#6]
Trying to run ./validate_api fails with a segmentation fault.
Back-tracing with gdb reveals that it tries to access the nested function definition inside BOOT_TEST/BARE_TEST{}, yielding 
invalid memory.

Tested on
Ubutnu 20.04, kernel 5.4 LTS, gcc 9.2
Manjaro Linux kernels 5.4 5.6 5.7 5.8 5.10 gcc 10.2
Arch Linux 5.9.8 gcc 10.2
Ubuntu lxc on host w/ kernel 5.9.8

Any system with kernel > 5.7 fails even the basic_test suite. 
All same cause => seg fault while accessing nested functions inside the BOOT/BARE_TEST macro

**Comment by Kallinteris-Andreas** [comment]
can verify 
it does not work on my 
5.14 linux (arch linux)
5.10 linux (Manjaro VM)

but it works on 
5.0 linux (ubuntu 18.04)
5.4 linux (Manjaro VM)

**Comment by Kallinteris-Andreas** [comment]
Can verify that after 27-10-21 update it works fine on
 5.14 linux (arch linux)

**Comment by the-rectifier** [comment]
can also confirm, closing
